# Generated by Django 2.1.1 on 2018-09-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180925_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='active',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='staff',
        ),
    ]
