# Generated by Django 2.1.1 on 2018-09-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180925_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_actives',
            field=models.BooleanField(default=True),
        ),
    ]
