# Generated by Django 2.1.5 on 2019-01-13 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='leave_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
